version: '3'

services: 

  #PHP Services
  test_app:
    container_name: test-app
    build: 
      context: .
      dockerfile: Dockerfile
    image: chillytaka/php7.4-pgsql
    tty: true
    ports:
      - "8080:80"
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html/
    networks: 
      - app_network

  #Firebird DB Services
  test_db:
    container_name: test-db
    image: postgres:13 
    tty: true
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: 123456
    volumes: 
      - ./database:/var/lib/postgresql/data
    networks: 
      - app_network


networks: 
  app_network:
    driver: bridge
